(function(){
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], KEY='aurelia_admin_data_v3';
const defaults={settings:{store:'Aurélia Paris',currency:'LKR',email:'care@aurelia.lk',announcement:'Discover refined fragrance rituals.',lowstock:8,tax:18},pages:['index.html','shop.html','about.html','blog.html','gallery.html','contact.html','account.html','wishlist.html','feedback.html'].map((file,i)=>({file,title:['A World of Fragrance','Shop Aurélia','Our Story','Beauty Journal','The Collection','Contact Aurélia','My Account','Your Wishlist','Customer Feedback'][i],description:['Discover elegant fragrances created to make every moment unforgettable.','Explore our curated fragrance collection.','The story, craft and spirit behind Aurélia Paris.','Stories, guides, and inspiration for choosing and enjoying your perfect fragrance.','A visual celebration of scent, detail and artistry.','We would love to hear from you.','View your profile, purchases and order history.','Save the fragrances you love.','What our customers say about their Aurélia experience.'][i],announcement:''})),products:[
{id:1,name:'Noir Élégance',sku:'AUR-001',price:28500,cost:15200,stock:14,discount:0,status:'Active',image:'images/img_2-3-1-300x360.jpg'},
{id:2,name:'Rose Lumière',sku:'AUR-002',price:24900,cost:13100,stock:6,discount:10,status:'Active',image:'images/img_2-4-300x360.jpg'},
{id:3,name:'Velvet Amber',sku:'AUR-003',price:31900,cost:17700,stock:21,discount:0,status:'Active',image:'images/img_2-5-300x360.jpg'},
{id:4,name:'Jardin Blanc',sku:'AUR-004',price:27500,cost:14600,stock:4,discount:15,status:'Active',image:'images/img_2-6-300x360.jpg'}],
customers:[{id:1,name:'Amaya Silva',email:'amaya@example.com',phone:'077 123 4567',joined:'2026-05-12',orders:4,spent:108400,status:'Active'},{id:2,name:'Nethmi Perera',email:'nethmi@example.com',phone:'071 551 9002',joined:'2026-06-03',orders:2,spent:56800,status:'VIP'},{id:3,name:'Kavindu Jayasena',email:'kavindu@example.com',phone:'075 222 8100',joined:'2026-07-18',orders:1,spent:24900,status:'Active'}],
orders:[{id:'AUR-1048',customer:'Amaya Silva',items:2,date:'2026-08-05',total:53400,status:'Processing'},{id:'AUR-1047',customer:'Nethmi Perera',items:1,date:'2026-08-04',total:31900,status:'Completed'},{id:'AUR-1046',customer:'Kavindu Jayasena',items:1,date:'2026-08-03',total:24900,status:'Shipped'},{id:'AUR-1045',customer:'Amaya Silva',items:2,date:'2026-08-01',total:55900,status:'Completed'}],
sales:[{month:'Mar',revenue:218000,cost:116000},{month:'Apr',revenue:284000,cost:147000},{month:'May',revenue:319000,cost:163000},{month:'Jun',revenue:371000,cost:192000},{month:'Jul',revenue:428000,cost:219000},{month:'Aug',revenue:486000,cost:247000}],
feedback:[{id:1,name:'Shenali',rating:5,text:'The packaging was beautiful and the fragrance feels incredibly refined.',date:'2026-08-04',status:'Published'},{id:2,name:'Dinuka',rating:4,text:'Fast delivery and very helpful guidance when choosing a gift.',date:'2026-08-02',status:'Published'},{id:3,name:'Mihiri',rating:5,text:'A premium experience from browsing to unboxing. I will order again.',date:'2026-07-29',status:'Published'}],
issues:[{id:'SUP-21',customer:'Amaya Silva',subject:'Delivery update request',message:'Customer requested an updated delivery time.',status:'Open'},{id:'SUP-20',customer:'Nethmi Perera',subject:'Gift note correction',message:'Change the recipient name on the gift card.',status:'In progress'},{id:'SUP-19',customer:'Kavindu Jayasena',subject:'Account access',message:'Password reset assistance completed.',status:'Resolved'}],notifications:[{title:'Weekend Collection',message:'Explore selected fragrances with complimentary gift wrapping.',audience:'All customers',date:'2026-08-02',status:'Published'}]};
let data=load(), currentReport='';
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data)); localStorage.setItem('aurelia_page_overrides',JSON.stringify(data.pages)); localStorage.setItem('admin_products',JSON.stringify(data.products)); localStorage.setItem('customerFeedbacks',JSON.stringify(data.feedback));}
function money(n){return (data.settings.currency||'LKR')+' '+Number(n||0).toLocaleString()}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function download(text,name,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function modal(html){$('#modal-content').innerHTML=html;$('#modal').hidden=false}
function closeModal(){if($('#modal'))$('#modal').hidden=true}
function initLogin(){const f=$('#admin-login-form');if(!f)return;$('#toggle-password')?.addEventListener('click',e=>{const p=$('#admin-password');p.type=p.type==='password'?'text':'password';e.target.textContent=p.type==='password'?'Show':'Hide'});f.onsubmit=e=>{e.preventDefault();if($('#admin-username').value==='admin'&&$('#admin-password').value==='admin@123'){sessionStorage.setItem('aurelia_admin_auth','1');location.href='dmindashboard.html'}else{const x=$('#admin-login-error');x.hidden=false;x.textContent='The username or password is incorrect.'}}}
function protect(){if(location.pathname.includes('dmindashboard')&&sessionStorage.getItem('aurelia_admin_auth')!=='1')location.href='login.html'}
function nav(){ $$('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.view)); $$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go)); $('#mobile-menu')?.addEventListener('click',()=>$('#sidebar').classList.toggle('open')); $('#admin-logout')?.addEventListener('click',()=>{sessionStorage.removeItem('aurelia_admin_auth');location.href='login.html'});$('#modal-close')?.addEventListener('click',closeModal);$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});}
function show(v){$$('.admin-view').forEach(x=>x.classList.remove('active'));$('#view-'+v)?.classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const b=$(`.nav-item[data-view="${v}"]`);$('#view-title').textContent=b?b.textContent.trim():'Dashboard';$('#sidebar').classList.remove('open');renderAll()}
function metrics(el,arr){$(el).innerHTML=arr.map(x=>`<article class="metric-card"><span class="metric-icon">${x.i}</span><small>${x.l}</small><h3>${x.v}</h3><em>${x.s||'Live data'}</em></article>`).join('')}
function renderOverview(){const revenue=data.sales.reduce((a,b)=>a+b.revenue,0),profit=data.sales.reduce((a,b)=>a+b.revenue-b.cost,0);metrics('#metric-grid',[{i:'↗',l:'TOTAL REVENUE',v:money(revenue),s:'+12.8% trend'},{i:'◇',l:'NET PROFIT',v:money(profit),s:'+9.4% trend'},{i:'≡',l:'TOTAL ORDERS',v:data.orders.length,s:'Updated now'},{i:'☆',l:'AVG. RATING',v:(data.feedback.reduce((a,b)=>a+b.rating,0)/Math.max(1,data.feedback.length)).toFixed(1),s:data.feedback.length+' reviews'}]);drawLine('sales-canvas',data.sales.map(x=>x.revenue),data.sales.map(x=>x.month));$('#recent-orders').innerHTML=data.orders.slice(0,5).map(orderRow).join('');const counts={Completed:0,Processing:0,Shipped:0,Pending:0};data.orders.forEach(o=>counts[o.status]=(counts[o.status]||0)+1);const total=data.orders.length||1, a=counts.Completed/total*100,b=(counts.Completed+counts.Processing)/total*100,c=(counts.Completed+counts.Processing+counts.Shipped)/total*100;$('#order-donut').innerHTML=`<div class="donut" style="background:conic-gradient(#b78b58 0 ${a}%,#252525 ${a}% ${b}%,#9f9a92 ${b}% ${c}%,#e6ded3 ${c}% 100%)"><div class="donut-label"><b>${total}</b><small>Orders</small></div></div>`;const avg=(data.feedback.reduce((a,b)=>a+b.rating,0)/Math.max(1,data.feedback.length)).toFixed(1);$('#feedback-summary').innerHTML=`<div class="feedback-score"><b>${avg}</b><div class="stars">★★★★★</div><p>${data.feedback.length} customer reviews</p></div>`+[5,4,3,2,1].map(r=>{let n=data.feedback.filter(x=>x.rating===r).length,p=n/Math.max(1,data.feedback.length)*100;return `<div class="rating-row"><span>${r}★</span><div class="bar"><i style="width:${p}%"></i></div><span>${n}</span></div>`}).join('')}
function drawLine(id,vals,labels,vals2){const c=document.getElementById(id);if(!c)return;const ctx=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=(parseInt(c.getAttribute('height'))||260)*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);const W=c.clientWidth,H=h/devicePixelRatio,p=35,max=Math.max(...vals,...(vals2||[]),1);ctx.clearRect(0,0,W,H);ctx.strokeStyle='#e8e1d7';ctx.lineWidth=1;for(let i=0;i<5;i++){let y=p+(H-2*p)*i/4;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(W-p,y);ctx.stroke()}function line(a,color){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();a.forEach((v,i)=>{let x=p+(W-2*p)*(i/(a.length-1||1)),y=H-p-(H-2*p)*v/max;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}line(vals,'#b78b58');if(vals2)line(vals2,'#222');ctx.fillStyle='#777';ctx.font='11px Arial';labels.forEach((l,i)=>ctx.fillText(l,p+(W-2*p)*(i/(labels.length-1||1))-8,H-10))}
function orderRow(o){return `<tr><td><b>${o.id}</b></td><td>${esc(o.customer)}</td><td>${o.date}</td><td>${money(o.total)}</td><td><span class="status ${o.status}">${o.status}</span></td></tr>`}
function renderPages(filter=''){const list=data.pages.filter(p=>(p.file+p.title).toLowerCase().includes(filter.toLowerCase()));$('#page-list').innerHTML=list.map(p=>`<button class="page-record" data-file="${p.file}"><b>${esc(p.title)}</b><small>${p.file}</small></button>`).join('');$$('.page-record').forEach(b=>b.onclick=()=>editPage(b.dataset.file))}
function editPage(file){const p=data.pages.find(x=>x.file===file);if(!p)return;$('#content-empty').hidden=true;$('#content-editor').hidden=false;$('#edit-page-file').value=p.file;$('#edit-page-name').value=p.file;$('#edit-page-title').value=p.title||'';$('#edit-page-description').value=p.description||'';$('#edit-page-announcement').value=p.announcement||'';$$('.page-record').forEach(x=>x.classList.toggle('active',x.dataset.file===file))}
function initContent(){$('#page-search').oninput=e=>renderPages(e.target.value);$('#save-page-content').onclick=()=>{const p=data.pages.find(x=>x.file===$('#edit-page-file').value);Object.assign(p,{title:$('#edit-page-title').value,description:$('#edit-page-description').value,announcement:$('#edit-page-announcement').value});save();toast('Page content saved')};$('#open-page').onclick=()=>window.open($('#edit-page-file').value,'_blank');$('#remove-page-record').onclick=()=>{data.pages=data.pages.filter(x=>x.file!==$('#edit-page-file').value);save();renderPages();$('#content-editor').hidden=true;$('#content-empty').hidden=false};$('#load-html').onclick=async()=>{try{$('#raw-html-editor').value=await fetch($('#edit-page-file').value).then(r=>r.text());toast('HTML loaded')}catch(e){toast('Serve the site through HTTP to load files')}};$('#download-html').onclick=()=>download($('#raw-html-editor').value,$('#edit-page-file').value,'text/html');$('#add-page-record').onclick=()=>modal(`<h2>Register a new page</h2><form id="page-add-form"><label>HTML file name</label><input id="new-page-file" placeholder="new-page.html" required><label>Page title</label><input id="new-page-title" required><label>Description</label><textarea id="new-page-desc"></textarea><button class="primary-btn full">Add page record</button></form>`);document.addEventListener('submit',e=>{if(e.target.id==='page-add-form'){e.preventDefault();data.pages.push({file:$('#new-page-file').value,title:$('#new-page-title').value,description:$('#new-page-desc').value,announcement:''});save();closeModal();renderPages();toast('Page registered')}})}
function renderProducts(){const q=($('#product-search')?.value||'').toLowerCase(),f=$('#product-filter')?.value||'all',items=data.products.filter(p=>(p.name+p.sku).toLowerCase().includes(q)&&(f==='all'||f==='low'&&p.stock<=data.settings.lowstock||f==='discount'&&p.discount>0));metrics('#product-metrics',[{i:'□',l:'PRODUCTS',v:data.products.length},{i:'!',l:'LOW STOCK',v:data.products.filter(p=>p.stock<=data.settings.lowstock).length},{i:'%',l:'DISCOUNTED',v:data.products.filter(p=>p.discount>0).length}]);$('#product-table').innerHTML=items.map(p=>`<tr><td><div class="product-cell"><img src="${p.image||'images/logo.png'}"><b>${esc(p.name)}</b></div></td><td>${p.sku}</td><td>${money(p.price)}</td><td>${p.discount}%</td><td class="${p.stock<=data.settings.lowstock?'low-stock':''}">${p.stock}</td><td><span class="status ${p.status}">${p.status}</span></td><td class="table-actions"><button onclick="AureliaAdmin.editProduct(${p.id})">Edit</button> · <button onclick="AureliaAdmin.deleteProduct(${p.id})">Delete</button></td></tr>`).join('')}
function productForm(p={}){modal(`<h2>${p.id?'Edit':'Add'} product</h2><form id="product-form-modal"><input type="hidden" id="pf-id" value="${p.id||''}"><label>Product name</label><input id="pf-name" value="${esc(p.name||'')}" required><div class="form-grid"><div><label>SKU</label><input id="pf-sku" value="${esc(p.sku||'')}" required><label>Selling price</label><input id="pf-price" type="number" value="${p.price||''}" required><label>Cost price</label><input id="pf-cost" type="number" value="${p.cost||''}"></div><div><label>Stock</label><input id="pf-stock" type="number" value="${p.stock||0}"><label>Discount %</label><input id="pf-discount" type="number" value="${p.discount||0}"><label>Image path</label><input id="pf-image" value="${esc(p.image||'')}"></div></div><button class="primary-btn full">Save product</button></form>`)}
function initProducts(){$('#new-product').onclick=()=>productForm();$('#product-search').oninput=renderProducts;$('#product-filter').onchange=renderProducts;$('#bulk-discount').onclick=()=>{const pct=prompt('Discount percentage for all products','10');if(pct!==null){data.products.forEach(p=>p.discount=Math.max(0,Math.min(100,+pct||0)));save();renderProducts();toast('Store discount updated')}};document.addEventListener('submit',e=>{if(e.target.id==='product-form-modal'){e.preventDefault();const id=+$('#pf-id').value,obj={id:id||Date.now(),name:$('#pf-name').value,sku:$('#pf-sku').value,price:+$('#pf-price').value,cost:+$('#pf-cost').value,stock:+$('#pf-stock').value,discount:+$('#pf-discount').value,status:'Active',image:$('#pf-image').value};if(id)data.products[data.products.findIndex(x=>x.id===id)]=obj;else data.products.push(obj);save();closeModal();renderProducts();toast('Product saved')}})}
function renderSales(){const rev=data.sales.reduce((a,b)=>a+b.revenue,0),cost=data.sales.reduce((a,b)=>a+b.cost,0);metrics('#sales-metrics',[{i:'↗',l:'REVENUE',v:money(rev)},{i:'−',l:'COST',v:money(cost)},{i:'◇',l:'PROFIT',v:money(rev-cost)},{i:'%',l:'MARGIN',v:Math.round((rev-cost)/Math.max(1,rev)*100)+'%'}]);drawLine('profit-canvas',data.sales.map(x=>x.revenue),data.sales.map(x=>x.month),data.sales.map(x=>x.revenue-x.cost));const tops=[...data.products].sort((a,b)=>b.price-b.price).slice(0,5);$('#top-products').innerHTML=tops.map((p,i)=>`<div class="top-list-item"><span>${i+1}. ${esc(p.name)}</span><b>${money(p.price)}</b></div>`).join('')}
function initSales(){const add=()=>modal(`<h2>Record monthly sale</h2><form id="sale-form"><label>Month</label><input id="sale-month" placeholder="Sep" required><label>Revenue</label><input id="sale-revenue" type="number" required><label>Cost</label><input id="sale-cost" type="number" required><button class="primary-btn full">Save sale</button></form>`);$('#add-sale').onclick=add;document.addEventListener('submit',e=>{if(e.target.id==='sale-form'){e.preventDefault();data.sales.push({month:$('#sale-month').value,revenue:+$('#sale-revenue').value,cost:+$('#sale-cost').value});save();closeModal();renderSales();toast('Sale recorded')}})}
function renderOrders(){const q=($('#order-search')?.value||'').toLowerCase(),f=$('#order-filter')?.value||'all';$('#order-table').innerHTML=data.orders.filter(o=>(o.id+o.customer).toLowerCase().includes(q)&&(f==='all'||o.status===f)).map(o=>`<tr><td><b>${o.id}</b></td><td>${esc(o.customer)}</td><td>${o.items}</td><td>${o.date}</td><td>${money(o.total)}</td><td><select onchange="AureliaAdmin.orderStatus('${o.id}',this.value)">${['Pending','Processing','Shipped','Completed','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td><td class="table-actions"><button onclick="AureliaAdmin.deleteOrder('${o.id}')">Delete</button></td></tr>`).join('')}
function initOrders(){ $('#order-search').oninput=renderOrders;$('#order-filter').onchange=renderOrders;$('#new-order').onclick=()=>modal(`<h2>Create order</h2><form id="order-form"><label>Customer</label><input id="of-customer" required><label>Number of items</label><input id="of-items" type="number" value="1"><label>Total</label><input id="of-total" type="number" required><button class="primary-btn full">Create order</button></form>`);document.addEventListener('submit',e=>{if(e.target.id==='order-form'){e.preventDefault();data.orders.unshift({id:'AUR-'+(1049+data.orders.length),customer:$('#of-customer').value,items:+$('#of-items').value,date:new Date().toISOString().slice(0,10),total:+$('#of-total').value,status:'Pending'});save();closeModal();renderOrders();toast('Order created')}})}
function renderFeedback(){const q=($('#feedback-search')?.value||'').toLowerCase(),f=$('#feedback-filter')?.value||'all',avg=(data.feedback.reduce((a,b)=>a+b.rating,0)/Math.max(1,data.feedback.length)).toFixed(1);metrics('#feedback-metrics',[{i:'☆',l:'AVERAGE RATING',v:avg},{i:'○',l:'TOTAL REVIEWS',v:data.feedback.length},{i:'!',l:'NEEDS REVIEW',v:data.feedback.filter(x=>x.rating<=3).length}]);$('#feedback-admin-list').innerHTML=data.feedback.filter(x=>(x.name+x.text).toLowerCase().includes(q)&&(f==='all'||f==='low'&&x.rating<=3||+f===x.rating)).map(x=>`<article class="feedback-admin-card"><div class="stars">${'★'.repeat(x.rating)}${'☆'.repeat(5-x.rating)}</div><blockquote>“${esc(x.text)}”</blockquote><div class="card-foot"><span><b>${esc(x.name)}</b><br><small>${x.date}</small></span><span><button class="secondary-btn" onclick="AureliaAdmin.toggleFeedback(${x.id})">${x.status==='Published'?'Hide':'Publish'}</button> <button class="danger-link" onclick="AureliaAdmin.deleteFeedback(${x.id})">Delete</button></span></div></article>`).join('')}
function initFeedback(){ $('#feedback-search').oninput=renderFeedback;$('#feedback-filter').onchange=renderFeedback}
function renderCustomers(){const q=($('#customer-search')?.value||'').toLowerCase();$('#customer-table').innerHTML=data.customers.filter(c=>(c.name+c.email+c.phone).toLowerCase().includes(q)).map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${c.email}<br><small>${c.phone}</small></td><td>${c.joined}</td><td>${c.orders}</td><td>${money(c.spent)}</td><td><span class="status ${c.status}">${c.status}</span></td><td class="table-actions"><button onclick="AureliaAdmin.editCustomer(${c.id})">Edit</button> · <button onclick="AureliaAdmin.deleteCustomer(${c.id})">Delete</button></td></tr>`).join('')}
function customerForm(c={}){modal(`<h2>${c.id?'Edit':'Add'} customer</h2><form id="customer-form-modal"><input type="hidden" id="cf-id" value="${c.id||''}"><label>Name</label><input id="cf-name" value="${esc(c.name||'')}" required><label>Email</label><input id="cf-email" type="email" value="${esc(c.email||'')}" required><label>Phone</label><input id="cf-phone" value="${esc(c.phone||'')}"><label>Status</label><select id="cf-status">${['Active','VIP','Blocked'].map(s=>`<option ${s===c.status?'selected':''}>${s}</option>`).join('')}</select><button class="primary-btn full">Save customer</button></form>`)}
function initCustomers(){ $('#customer-search').oninput=renderCustomers;$('#add-customer').onclick=()=>customerForm();$('#export-customers').onclick=()=>download('Name,Email,Phone,Joined,Orders,Spent,Status\n'+data.customers.map(c=>[c.name,c.email,c.phone,c.joined,c.orders,c.spent,c.status].join(',')).join('\n'),'customers.csv','text/csv');document.addEventListener('submit',e=>{if(e.target.id==='customer-form-modal'){e.preventDefault();const id=+$('#cf-id').value,obj={id:id||Date.now(),name:$('#cf-name').value,email:$('#cf-email').value,phone:$('#cf-phone').value,joined:id?data.customers.find(x=>x.id===id).joined:new Date().toISOString().slice(0,10),orders:id?data.customers.find(x=>x.id===id).orders:0,spent:id?data.customers.find(x=>x.id===id).spent:0,status:$('#cf-status').value};if(id)data.customers[data.customers.findIndex(x=>x.id===id)]=obj;else data.customers.push(obj);save();closeModal();renderCustomers();toast('Customer saved')}})}
function renderIssues(){const groups=['Open','In progress','Resolved'];$('#support-board').innerHTML=groups.map(g=>`<div class="support-column"><h3>${g} <small>(${data.issues.filter(x=>x.status===g).length})</small></h3>${data.issues.filter(x=>x.status===g).map(x=>`<article class="support-card"><small>${x.id}</small><h4>${esc(x.subject)}</h4><b>${esc(x.customer)}</b><p>${esc(x.message)}</p><select onchange="AureliaAdmin.issueStatus('${x.id}',this.value)">${groups.map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select></article>`).join('')}</div>`).join('')}
function initIssues(){ $('#new-issue').onclick=()=>modal(`<h2>Create support case</h2><form id="issue-form"><label>Customer</label><input id="if-customer" required><label>Subject</label><input id="if-subject" required><label>Issue details</label><textarea id="if-message" required></textarea><button class="primary-btn full">Create case</button></form>`);document.addEventListener('submit',e=>{if(e.target.id==='issue-form'){e.preventDefault();data.issues.unshift({id:'SUP-'+(22+data.issues.length),customer:$('#if-customer').value,subject:$('#if-subject').value,message:$('#if-message').value,status:'Open'});save();closeModal();renderIssues();toast('Support case created')}})}
function renderNotifications(){$('#notification-history').innerHTML=data.notifications.map(n=>`<article class="notification-item"><h4>${esc(n.title)}</h4><p>${esc(n.message)}</p><small>${n.audience} · ${n.date} · ${n.status}</small></article>`).join('')}
function initNotifications(){ $('#notification-form').onsubmit=e=>{e.preventDefault();data.notifications.unshift({title:$('#notify-title').value,message:$('#notify-message').value,audience:$('#notify-audience').value,date:$('#notify-date').value||new Date().toISOString().slice(0,10),status:$('#notify-date').value?'Scheduled':'Published'});save();e.target.reset();renderNotifications();toast('Notification saved')};$('#quick-notification').onclick=()=>show('notifications')}
function createReport(type){currentReport=type;let html='',csv='';if(type==='monthly'){csv='Month,Revenue,Cost,Profit\n'+data.sales.map(x=>`${x.month},${x.revenue},${x.cost},${x.revenue-x.cost}`).join('\n');html='<table><tr><th>Month</th><th>Revenue</th><th>Cost</th><th>Profit</th></tr>'+data.sales.map(x=>`<tr><td>${x.month}</td><td>${money(x.revenue)}</td><td>${money(x.cost)}</td><td>${money(x.revenue-x.cost)}</td></tr>`).join('')+'</table>'}if(type==='products'){csv='Product,SKU,Price,Stock,Discount\n'+data.products.map(x=>`${x.name},${x.sku},${x.price},${x.stock},${x.discount}`).join('\n');html='<table><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th></tr>'+data.products.map(x=>`<tr><td>${x.name}</td><td>${x.sku}</td><td>${money(x.price)}</td><td>${x.stock}</td></tr>`).join('')+'</table>'}if(type==='customers'){csv='Name,Email,Orders,Spent,Status\n'+data.customers.map(x=>`${x.name},${x.email},${x.orders},${x.spent},${x.status}`).join('\n');html='<table><tr><th>Customer</th><th>Email</th><th>Orders</th><th>Spent</th></tr>'+data.customers.map(x=>`<tr><td>${x.name}</td><td>${x.email}</td><td>${x.orders}</td><td>${money(x.spent)}</td></tr>`).join('')+'</table>'}if(type==='feedback'){csv='Name,Rating,Date,Status,Feedback\n'+data.feedback.map(x=>`"${x.name}",${x.rating},${x.date},${x.status},"${x.text.replaceAll('"','""')}"`).join('\n');html='<table><tr><th>Name</th><th>Rating</th><th>Date</th><th>Status</th></tr>'+data.feedback.map(x=>`<tr><td>${x.name}</td><td>${x.rating}</td><td>${x.date}</td><td>${x.status}</td></tr>`).join('')+'</table>'}$('#report-output').innerHTML=html;$('#report-output').dataset.csv=csv}
function initReports(){$$('.report-card').forEach(b=>b.onclick=()=>createReport(b.dataset.report));$('#download-report').onclick=()=>{if(!currentReport)return toast('Select a report first');download($('#report-output').dataset.csv,currentReport+'-report.csv','text/csv')}}
function renderSettings(){ $('#setting-store').value=data.settings.store;$('#setting-currency').value=data.settings.currency;$('#setting-email').value=data.settings.email;$('#setting-announcement').value=data.settings.announcement;$('#setting-lowstock').value=data.settings.lowstock;$('#setting-tax').value=data.settings.tax}
function initSettings(){ $('#settings-form').onsubmit=e=>{e.preventDefault();data.settings={store:$('#setting-store').value,currency:$('#setting-currency').value,email:$('#setting-email').value,announcement:$('#setting-announcement').value,lowstock:+$('#setting-lowstock').value,tax:+$('#setting-tax').value};save();toast('Settings saved')};$('#backup-data').onclick=()=>download(JSON.stringify(data,null,2),'aurelia-admin-backup.json','application/json');$('#reset-data').onclick=()=>{if(confirm('Reset all dashboard data?')){localStorage.removeItem(KEY);data=structuredClone(defaults);save();renderAll();toast('Dashboard reset')}}}
function renderAll(){renderOverview();renderPages();renderProducts();renderSales();renderOrders();renderFeedback();renderCustomers();renderIssues();renderNotifications();renderSettings()}
window.AureliaAdmin={editProduct:id=>productForm(data.products.find(x=>x.id===id)),deleteProduct:id=>{if(confirm('Delete this product?')){data.products=data.products.filter(x=>x.id!==id);save();renderProducts()}},orderStatus:(id,s)=>{data.orders.find(x=>x.id===id).status=s;save();renderOrders()},deleteOrder:id=>{data.orders=data.orders.filter(x=>x.id!==id);save();renderOrders()},toggleFeedback:id=>{const x=data.feedback.find(x=>x.id===id);x.status=x.status==='Published'?'Hidden':'Published';save();renderFeedback()},deleteFeedback:id=>{data.feedback=data.feedback.filter(x=>x.id!==id);save();renderFeedback()},editCustomer:id=>customerForm(data.customers.find(x=>x.id===id)),deleteCustomer:id=>{data.customers=data.customers.filter(x=>x.id!==id);save();renderCustomers()},issueStatus:(id,s)=>{data.issues.find(x=>x.id===id).status=s;save();renderIssues()}};
protect();document.addEventListener('DOMContentLoaded',()=>{initLogin();if(!$('.admin-app'))return;save();nav();initContent();initProducts();initSales();initOrders();initFeedback();initCustomers();initIssues();initNotifications();initReports();initSettings();$('#current-date').textContent=new Intl.DateTimeFormat('en-LK',{dateStyle:'medium'}).format(new Date());renderAll();window.addEventListener('resize',()=>{renderOverview();renderSales()})});
})();
