(function(){
const KEY='aurelia_cms_overrides_v1', manifest=window.AURELIA_CMS_MANIFEST||[];
let current=manifest[0]?.file||'', overrides=load();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return {}}}
function save(){localStorage.setItem(KEY,JSON.stringify(overrides)); window.dispatchEvent(new StorageEvent('storage',{key:KEY,newValue:JSON.stringify(overrides)}));}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)}
function pageObj(){return manifest.find(p=>p.file===current)}
function renderPages(){const q=($('#cms-page-search')?.value||'').toLowerCase();const box=$('#cms-page-list');if(!box)return;box.innerHTML=manifest.filter(p=>(p.file+' '+p.title).toLowerCase().includes(q)).map(p=>`<button class="cms-page-btn ${p.file===current?'active':''}" data-cms-page="${p.file}"><b>${esc(p.title)}</b><small>${p.file} · ${p.entries.length} editable items</small></button>`).join('');$$('[data-cms-page]').forEach(b=>b.onclick=()=>{current=b.dataset.cmsPage;renderPages();renderEntries()})}
function val(e){return overrides[e.id]?.value ?? e.value}
function renderEntries(){const p=pageObj(),box=$('#cms-entry-list'),empty=$('#cms-empty');if(!box||!p)return;const q=($('#cms-entry-search')?.value||'').toLowerCase(),type=$('#cms-type-filter')?.value||'all';const list=p.entries.filter(e=>(type==='all'||e.type===type)&&((e.label||'')+' '+(e.value||'')+' '+e.id).toLowerCase().includes(q));empty.hidden=true;box.innerHTML=`<p class="cms-count">Showing ${list.length} of ${p.entries.length} editable items on <b>${p.file}</b></p>`+list.map(card).join('');bindCards()}
function card(e){const o=overrides[e.id]||{},hidden=o.hidden===true, value=val(e);if(e.type==='link')return `<article class="cms-entry-card ${hidden?'cms-hidden':''}" data-card="${e.id}"><div class="cms-entry-head"><div><small>Button / page link · ${e.tag}</small><br><code>${e.id}</code></div><span>${hidden?'Hidden':'Visible'}</span></div><label>Opens this local HTML file</label><input type="text" data-value="${e.id}" value="${esc(value)}" placeholder="example.html"><p class="cms-link-help">Use only a file included in this folder, such as <code>shop.html</code>, <code>about.html</code> or <code>index.html#section</code>.</p><div class="cms-entry-actions"><button class="primary-btn" data-save="${e.id}">Save link path</button><button class="secondary-btn" data-test-link="${e.id}">Test link</button><button class="secondary-btn" data-toggle="${e.id}">${hidden?'Show element':'Hide element'}</button><button class="danger-link" data-reset="${e.id}">Restore original</button></div></article>`;if(e.type==='text')return `<article class="cms-entry-card ${hidden?'cms-hidden':''}" data-card="${e.id}"><div class="cms-entry-head"><div><small>Text · ${e.tag}</small><br><code>${e.id}</code></div><span>${hidden?'Hidden':'Visible'}</span></div><textarea data-value="${e.id}">${esc(value)}</textarea><div class="cms-entry-actions"><button class="primary-btn" data-save="${e.id}">Save text</button><button class="secondary-btn" data-toggle="${e.id}">${hidden?'Show element':'Hide element'}</button><button class="danger-link" data-reset="${e.id}">Restore original</button></div></article>`;
const src=value;return `<article class="cms-entry-card ${hidden?'cms-hidden':''}" data-card="${e.id}"><div class="cms-entry-head"><div><small>${e.type==='background'?'Background':'Image'}</small><br><code>${e.id}</code></div><span>${hidden?'Hidden':'Visible'}</span></div><img class="cms-image-preview" src="${esc(src)}" onerror="this.style.display='none'"><div class="cms-upload-row"><input type="text" data-value="${e.id}" value="${esc(src)}" placeholder="Image URL or uploaded data"><label class="secondary-btn file-button">Upload image<input type="file" data-upload="${e.id}" accept="image/*" hidden></label></div>${e.type==='image'?`<label>Alternative text</label><input type="text" data-alt="${e.id}" value="${esc(o.alt??e.alt??'')}">`:''}<div class="cms-entry-actions"><button class="primary-btn" data-save="${e.id}">Save image</button><button class="secondary-btn" data-toggle="${e.id}">${hidden?'Show element':'Hide element'}</button><button class="danger-link" data-reset="${e.id}">Restore original</button></div></article>`}
function bindCards(){$$('[data-save]').forEach(b=>b.onclick=()=>{const id=b.dataset.save,e=manifest.flatMap(p=>p.entries).find(x=>x.id===id),input=$(`[data-value="${id}"]`),value=input.value.trim();if(e?.type==='link'){const clean=value.split('#')[0].split('?')[0];if(!clean.toLowerCase().endsWith('.html'))return toast('Link must point to a local .html file');if(/^(https?:|mailto:|tel:|javascript:|\/\/)/i.test(value))return toast('Online links are not allowed');}overrides[id]={...(overrides[id]||{}),value:e?.type==='link'?value:input.value};const alt=$(`[data-alt="${id}"]`);if(alt)overrides[id].alt=alt.value;save();toast(e?.type==='link'?'Button link updated':'Website content updated')});$$('[data-test-link]').forEach(b=>b.onclick=()=>{const id=b.dataset.testLink,value=$(`[data-value="${id}"]`).value.trim();if(value)window.open(value,'_blank')});$$('[data-toggle]').forEach(b=>b.onclick=()=>{const id=b.dataset.toggle;overrides[id]={...(overrides[id]||{}),hidden:!(overrides[id]?.hidden===true)};save();renderEntries()});$$('[data-reset]').forEach(b=>b.onclick=()=>{delete overrides[b.dataset.reset];save();renderEntries();toast('Original content restored')});$$('[data-upload]').forEach(inp=>inp.onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>2.5*1024*1024)return toast('Choose an image smaller than 2.5 MB');const r=new FileReader();r.onload=()=>{const id=inp.dataset.upload;$(`[data-value="${id}"]`).value=r.result;const im=inp.closest('.cms-entry-card').querySelector('img');im.src=r.result;im.style.display='block'};r.readAsDataURL(file)})}
function exportData(){const blob=new Blob([JSON.stringify({exported:new Date().toISOString(),overrides},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aurelia-website-content.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function init(){if(!$('#cms-page-list'))return;renderPages();renderEntries();$('#cms-page-search').oninput=renderPages;$('#cms-entry-search').oninput=renderEntries;$('#cms-type-filter').onchange=renderEntries;$('#cms-preview').onclick=()=>window.open(current,'_blank');$('#export-cms').onclick=exportData;$('#import-cms').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);overrides=x.overrides||x;save();renderEntries();toast('Website content imported')}catch(err){toast('Invalid content backup')}};r.readAsText(f)}}
document.addEventListener('DOMContentLoaded',init);
})();
